// Static OASF taxonomy — sourced from https://schema.oasf.outshift.com/skills and /domains

function toLabel(key: string): string {
  const overrides: Record<string, string> = {
    ai: "AI",
    api: "API",
    iot: "IoT",
    qa: "QA",
    pos: "POS",
    rpa: "RPA",
    ci: "CI",
    cd: "CD",
    aws: "AWS",
    gcp: "GCP",
    azure: "Azure",
    mlops: "MLOps",
    devops: "DevOps",
    defi: "DeFi",
    did: "DID",
    "3d": "3D",
    voip: "VoIP",
    nlp: "NLP",
  };
  return key
    .split("_")
    .map(
      (w) =>
        overrides[w.toLowerCase()] ?? w.charAt(0).toUpperCase() + w.slice(1),
    )
    .join(" ");
}

const SKILL_KEYS = [
  "natural_language_understanding",
  "natural_language_generation",
  "information_retrieval_synthesis",
  "creative_content",
  "language_translation",
  "personalization",
  "analytical_reasoning",
  "ethical_interaction",
  "text_classification",
  "feature_extraction",
  "token_classification",
  "image_segmentation",
  "video_classification",
  "image_classification",
  "object_detection",
  "keypoint_detection",
  "image_generation",
  "depth_estimation",
  "image_feature_extraction",
  "mask_generation",
  "image_to_image",
  "image_to_3d",
  "audio_classification",
  "audio_to_audio",
  "tabular_classification",
  "tabular_regression",
  "mathematical_reasoning",
  "coding_skills",
  "retrieval_of_information",
  "document_or_database_question_answering",
  "generation_of_any",
  "image_processing",
  "audio_processing",
  "any_to_any",
  "threat_detection",
  "vulnerability_analysis",
  "secret_leak_detection",
  "privacy_risk_assessment",
  "data_cleaning",
  "schema_inference",
  "feature_engineering",
  "data_transformation_pipeline",
  "data_quality_assessment",
  "task_decomposition",
  "role_assignment",
  "multi_agent_planning",
  "agent_coordination",
  "negotiation_resolution",
  "benchmark_execution",
  "test_case_generation",
  "quality_evaluation",
  "anomaly_detection",
  "performance_monitoring",
  "infrastructure_provisioning",
  "deployment_orchestration",
  "ci_cd_configuration",
  "model_versioning",
  "monitoring_alerting",
  "policy_mapping",
  "compliance_assessment",
  "audit_trail_summarization",
  "risk_classification",
  "api_schema_understanding",
  "workflow_automation",
  "tool_use_planning",
  "script_integration",
  "strategic_planning",
  "long_horizon_reasoning",
  "chain_of_thought_structuring",
  "hypothesis_generation",
  "contextual_comprehension",
  "semantic_understanding",
  "entity_recognition",
  "text_completion",
  "summarization",
  "paraphrasing",
  "dialogue_generation",
  "question_generation",
  "text_style_transfer",
  "story_generation",
  "fact_extraction",
  "question_answering",
  "knowledge_synthesis",
  "sentence_similarity",
  "document_passage_retrieval",
  "information_retrieval_synthesis_search",
  "storytelling",
  "poetry_writing",
  "translation",
  "multilingual_understanding",
  "user_adaptation",
  "style_adjustment",
  "inference_deduction",
  "problem_solving",
  "fact_verification",
  "bias_mitigation",
  "content_moderation",
  "topic_labeling",
  "sentiment_analysis",
  "natural_language_inference",
  "model_feature_extraction",
  "named_entity_recognition",
  "pos_tagging",
  "pure_math_operations",
  "math_word_problems",
  "geometry",
  "theorem_proving",
  "text_to_code",
  "code_to_docstrings",
  "code_templates",
  "code_optimization",
  "indexing",
  "retrieval_of_information_search",
  "document_retrieval",
  "image_to_text",
  "text_to_image",
  "text_to_video",
  "text_to_3d",
  "visual_qa",
  "text_to_speech",
  "speech_recognition",
] as const;

const DOMAIN_KEYS = [
  "internet_of_things",
  "software_engineering",
  "networking",
  "data_science",
  "cloud_computing",
  "information_technology",
  "security",
  "communication_systems",
  "blockchain",
  "process_automation",
  "banking",
  "finance",
  "investment_services",
  "consumer_goods",
  "retail",
  "biotechnology",
  "pharmaceutical_research",
  "genomics",
  "bioinformatics",
  "molecular_biology",
  "online_safety",
  "content_moderation",
  "fraud_prevention",
  "data_privacy",
  "risk_management",
  "recruitment",
  "employee_relations",
  "training_and_development",
  "compensation_and_benefits",
  "hr_analytics",
  "e_learning",
  "curriculum_design",
  "learning_management_systems",
  "educational_technology",
  "pedagogy",
  "automation",
  "robotics",
  "supply_chain_management",
  "lean_manufacturing",
  "process_engineering",
  "logistics",
  "automotive",
  "public_transit",
  "supply_chain",
  "freight",
  "autonomous_vehicles",
  "medical_technology",
  "telemedicine",
  "healthcare_informatics",
  "patient_management_systems",
  "health_information_systems",
  "contract_law",
  "intellectual_property",
  "regulatory_compliance",
  "litigation",
  "legal_research",
  "corporate_governance",
  "agricultural_technology",
  "crop_management",
  "livestock_management",
  "precision_agriculture",
  "sustainable_farming",
  "energy_management",
  "energy_storage",
  "oil_and_gas",
  "power_generation",
  "renewable_energy",
  "smart_grids",
  "broadcasting",
  "content_creation",
  "digital_media",
  "gaming",
  "publishing",
  "streaming_services",
  "construction",
  "facilities_management",
  "property_management",
  "proptech",
  "real_estate_investment",
  "urban_planning",
  "event_planning",
  "food_and_beverage",
  "hospitality_technology",
  "hotel_management",
  "tourism_management",
  "travel_services",
  "internet_services",
  "iot_connectivity",
  "network_infrastructure",
  "telecom_operations",
  "voip_and_unified_communications",
  "wireless_communications",
  "climate_science",
  "conservation_biology",
  "ecology",
  "environmental_monitoring",
  "environmental_policy",
  "sustainability",
  "civic_engagement",
  "e_government",
  "emergency_management",
  "public_administration",
  "public_infrastructure",
  "public_policy",
  "grant_management",
  "innovation_management",
  "laboratory_management",
  "product_development",
  "research_data_management",
  "scientific_research",
  "customer_experience",
  "inventory_management",
  "online_retail",
  "order_fulfillment",
  "point_of_sale",
  "retail_analytics",
  "case_management",
  "child_and_family_services",
  "community_outreach",
  "disability_services",
  "housing_assistance",
  "mental_health_services",
  "athletic_training",
  "fitness_and_wellness",
  "sports_analytics",
  "sports_management",
  "sports_medicine",
  "sports_technology",
  "actuarial_science",
  "claims_processing",
  "insurance_sales",
  "insurtech",
  "policy_management",
  "underwriting",
  "advertising",
  "brand_management",
  "digital_marketing",
  "market_research",
  "marketing_analytics",
  "marketing_automation",
  "iot_devices",
  "iot_security",
  "iot_networks",
  "smart_homes",
  "industrial_iot",
  "software_development",
  "devops",
  "quality_assurance",
  "apis_integration",
  "mlops",
  "network_operations",
  "network_management",
  "network_protocols",
  "network_architecture",
  "network_security",
  "big_data",
  "data_visualization",
  "data_engineering",
  "aws",
  "azure",
  "gcp",
  "performance_analysis",
  "system_administration",
  "database_administration",
  "help_desk_support",
  "cybersecurity",
  "data_security",
  "application_security",
  "cyber_network_security",
  "identity_management",
  "incident_management",
  "telecommunication",
  "wireless_communication",
  "signal_processing",
  "broadcasting_systems",
  "cryptocurrency",
  "defi",
  "smart_contracts",
  "rpa",
  "workflow_automation",
] as const;

export const OASF_SKILLS: { key: string; label: string }[] = SKILL_KEYS.map(
  (key) => ({
    key,
    label: toLabel(key),
  }),
);

export const OASF_DOMAINS: { key: string; label: string }[] = DOMAIN_KEYS.map(
  (key) => ({
    key,
    label: toLabel(key),
  }),
);
